### ISSUE TITLE
Video y-scrollable

### ISSUE THREAD

**Issue by xixixao** [owickstrom/the-monospace-web#4]
The video player on the demo site with its description (figuretext) is vertically scrollable, separately from the whole page.

I'm on iPhone 14 Pro Safari.

![image](https://github.com/user-attachments/assets/421d9229-5c88-45bd-8f3c-ba68e4f3f1b4)

**Comment by owickstrom** [comment]
I think this should be fixed now. Can you confirm?

**Comment by xixixao** [comment]
Fixed.
